service: translator

frameworkVersion: "=1.42.3"

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  environment:
    TRANSLATION_BUCKET_NAME:
      Ref: TranslationsBucket
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "translate:TranslateText"
        - "comprehend:DetectDominantLanguage"
        - "polly:SynthesizeSpeech"
        - "rekognition:DetectText"
        # - "rekognition:DetectLabels"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - Fn::GetAtt: [TranslationsBucket, Arn]
            - "/*"
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource:
        Fn::GetAtt: [TranslationsBucket, Arn]

functions:
  translate:
    handler: handler.translate
    timeout: 30
    events:
      - http:
          path: "/translate"
          method: post
          cors: true
  upload:
    handler: handler.upload
    events:
      - http:
          path: "/upload"
          method: get
          cors: true

resources:
  Resources:
    TranslationsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: translator-service-${self:provider.stage}-translations
        LifecycleConfiguration:
          Rules:
            - ExpirationInDays: 1
              Status: Enabled
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - PUT
              AllowedOrigins:
                - "*"

    TranslationsBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: TranslationsBucketPolicy
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action:
                - 's3:GetObject'
              Resource:
                Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - Ref: TranslationsBucket
                    - /translations/*
            - Sid: WriteAccessForSignedUrlUploads
              Effect: Allow
              Principal:
                AWS:
                  - Fn::GetAtt: [IamRoleLambdaExecution, Arn]
              Action:
                - 's3:PutObject'
              Resource:
                Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - Ref: TranslationsBucket
                    - /files/*
        Bucket:
          Ref: TranslationsBucket
